name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          echo "jore4 - event_name"
          echo ${{ github.event_name }}
          echo "jore5-end"

  now_it_is_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Now it is
        if: ${{ github.event_name == 'pushh' }}
        run: |
          date
          echo "jore4 - event_name"
          echo ${{ github.event_name }}
          echo "jore5-end"

  directory_content_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Directory content
        run: |
          ls -l